# Generated by Django 5.1.3 on 2024-12-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('priority', 'deadline')},
        ),
    ]
